apiVersion: apps/v1
kind: Deployment
metadata:
  name: synctree-portal-admin
  namespace: synctree
spec:
  replicas: 1
  selector:
    matchLabels:
      service: synctree-portal-admin
      app: portal-admin #label setting
  template:
    metadata:
      labels:
        service: synctree-portal-admin
        app: portal-admin #label setting
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  values:
                  - portal-admin
                  operator: In
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: synctree-portal-admin
        image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/ntuple-synctree/portal:2.0.2.10
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
              - SYS_ADMIN
              - DAC_READ_SEARCH
          privileged: true
        volumeMounts:
        - name: deploy-configmap
          mountPath: "/root/deploy"
        - name: nginx-portal-admin-conf
          mountPath: "/etc/nginx/sites-enabled"
        - name: log
          mountPath: "/home/ubuntu/apps/synctree-portal/logs"
        - name: user-storage
          mountPath: "/home/ubuntu/user-storage"
        - name: shared
          mountPath: "/home/ubuntu/shared" 
        command: ["/bin/bash", "-c", "sh /root/deploy/portal.sh && sh /root/deploy/deploy.sh"]
      initContainers:
      - name: log-dir-permission-fix
        image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/ntuple-synctree/busybox:1.0.0.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c","chmod -R 775 /mnt && chown -R root:www-data /mnt"]
        volumeMounts:
        - name: log 
          mountPath: "/mnt/logs"
        - name: user-storage
          mountPath: "/mnt/user-storage"
        - name: shared
          mountPath: "/mnt/shared"
      volumes:
      - name: deploy-configmap
        configMap:
          name: deploy-configmap
      - name: nginx-portal-admin-conf
        configMap:
          name: nginx-portal-admin-conf
          items:
            - key: portal-admin.conf
              path: portal-admin.conf
      - name: log
        hostPath:
          path: "/var/log/synctree/logs-group/portal-admin-log"
          type: DirectoryOrCreate 
      - name: user-storage
        hostPath:
          path: "/data/store"
          type: DirectoryOrCreate
      - name: shared
        hostPath:
          path: "/data/shared"
          type: DirectoryOrCreate
      imagePullSecrets:
        - name: private-repo
---
apiVersion: v1
kind: Service
metadata:
  name: synctree-portal-admin
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30184
    protocol: TCP
  selector:
    service: synctree-portal-admin
